import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const neueSans = localFont({
  src: [
    {
      path: "./fonts/neue-montreal-regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/neue-montreal-medium.otf",
      weight: "500",
      style: "medium",
    },
    {
      path: "./fonts/neue-montreal-bold.otf",
      weight: "700",
      style: "bold",
    },
  ],
  variable: "--font-neue-sans",
});

const fablabSans = localFont({
  src: [
    {
      path: "./fonts/fablab.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-fablab-sans",
});

const shootingStar = localFont({
  src: "./fonts/shooting-star.otf",
  weight: "400",
  style: "normal",
  variable: "--font-shootingStar",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`dark ${neueSans.variable} ${fablabSans.variable} ${shootingStar.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
