import type { Metadata } from "next";
import "./globals.css";
import { fablabSans, neueSans, shootingStar } from "@/assets/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`dark ${neueSans.variable} ${fablabSans.variable} ${shootingStar.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
